---
- hosts: deb_based
  user: root
  tasks:

  - name: add LTS repository to debian 6
    apt_repository: repo='deb http://ftp.debian.org/debian squeeze-lts main contrib non-free' state=present
    when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '6'

  - name: add LTS src repository to debian 6
    apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ squeeze-lts main contrib non-free' state=present
    when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '6'

   - name: upgrade bash
     apt:
       name=bash
       state=latest
       update_cache=yes

   - name: check bash fix
     command: env x='() { :;}; echo vulnerable' bash -c "echo this is a test"
     register: command_result
     failed_when: "'error' not in command_result.stderr"
       
