---
- hosts: debian

  user: root

  tasks:

   - name: upgrade keyring to avoid unknow key problem
     apt:
       name=debian-archive-keyring
       state=latest
       update_cache=yes
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '6'

   - name: add lts repository to debian 6
     apt_repository: repo='deb http://ftp.debian.org/debian squeeze-lts main contrib non-free' state=present
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '6'

   - name: add lts src repository to debian 6
     apt_repository: repo='deb-src http://ftp.fr.debian.org/debian/ squeeze-lts main contrib non-free' state=present
     when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '6'
